project:
  type: website

execute:
  echo: false     # Hide code blocks
  warning: false  # Suppress R warnings
  message: false  # Suppress R messages
  
website:
  title: "REPO-NAME"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tab-plots/index.qmd
        text: Plots
      - href: tab-tables/index.qmd
        text: Tables
    logo: images/uzh.png

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



